import React from "react";

import csvg from "../assets/lll.png";
import mapImg from "../assets//map.png";

import "../styles/crypto.css";

import Nav from "../Components/Nav";
import SubHeaders from "./subpages/SubHeaders";
import Footer from "./subpages/Footer";
import { MarketData } from "react-ts-tradingview-widgets";
import Entrepreneurs from "./subpages/Entrepreneurs";

function Crypto() {
  return (
    <div className="crypto-main-page">
      <Nav />
      <SubHeaders
        description={
          "Empowering Futures, Transforming Traditions: Crypto Pioneers on the Rise!"
        }
        header={"Crypto Market"}
      />
      <div className="crypto-section-wrapper">
        <h1>What Constitutes Cryptocurrencies?</h1>
        <div className="crypto-contenten-wrapper">
          <div className="crypto-section-1">
            <p>
              A cryptocurrency is a virtual currency crafted for seamless
              digital transactions between individuals. Existing solely as data
              and not tangible objects, you cannot physically hold a Bitcoin in
              your hand or secure Ethereum in a physical safe.
            </p>
            <h1>Market Indices</h1>
            <p>
              Decentralized cryptocurrencies are generated by the collective
              operation of the entire cryptocurrency system. The production rate
              is predetermined at the system's inception and is publicly
              disclosed. In contrast to centralized banking systems like the
              Federal Reserve, where currency supply is controlled by entities
              like corporate boards or governments through fiat money printing
              or digital ledger adjustments, decentralized cryptocurrencies
              operate independently. <br />
              <br /> When you own a Bitcoin, it signifies a consensus among
              every computer within the Bitcoin network that you are the
              legitimate owner. Crucially, it attests that the Bitcoin was
              validly created through the mining process.
            </p>
          </div>
          <div className="crypto-img-wrapper">
            <img src={csvg} alt="" />
          </div>
        </div>
        <div className="crypto-widgetWrapper">
          <MarketData />
        </div>
        <Entrepreneurs bckImg={mapImg} />
      </div>
      <Footer />
    </div>
  );
}

export default Crypto;
